# Example usage: ansible-playbook collections_demo/main.yml
# This playbook get information about NGINX using community.general collection
# https://github.com/ansible-collections/community.general/blob/main/plugins/modules/web_infrastructure/nginx_status_facts.py

---

- hosts: ubuntu_servers
  collections:
    - community.general
  tasks:
    - name: Gather facts from the device.
      nginx_status_facts:
        url: http://localhost/nginx_status
    - name: NGINX data
      debug: msg="{{ nginx_status_facts.data }}"
