# Example usage: ansible-playbook custom_module_demo/main.yml
# This playbook use a custom module to print the name

---

- name: Custom module test
  hosts: ubuntu_servers
  vars_prompt:
   - name: getName
     prompt: "Cual es tu nombre"
     private: no
     failed_when: getName is undefined
  tasks:
    - name: Python Execution
      my_python: yourName={{ getName }}
      register: result
    - name: dump test result
      debug: msg="{{ result }}"
    - name: Python Execution v2
      my_python_v2: 
        name: carlos
      register: result2
    - name: dump test result2
      debug: msg="{{ result2 }}"
    - name: run the new module
      my_python_v3:
        name: hello
        new: true
      register: testout
    - name: dump test output
      debug: msg="{{ testout }}"