# Example usage: ansible-playbook custom_module_demo/main.yml
# This playbook use a custom module to print the name

---

- name: Custom module test
  hosts: ubuntu_servers
  vars_prompt:
   - name: getName
     prompt: "Cual es tu nombre"
     private: no
     failed_when: getName is undefined
  tasks:
    - name: Python Execution
      my_python: yourName={{ getName }}
      register: result
    - debug: var=result
    - name: Python Execution v2
      my_python_v2: 
        name: carlos
      register: result2
    - debug: var=result2