---
- name: Var test
  hosts: ubuntu_servers
  vars:
    home_folder: home
    user: rdnovell
    item: file1
  tasks:
    - name: Test var use
      command: ls -ltr /{{ home_folder }}/{{ user }}/{{ item }}