# Example usage: ansible-playbook include_demo/main.yml
# This playbook use inlcude to call a play on other yml file

---

- name: Include test
  hosts: ubuntu_servers
  tasks:
    - name: Test service status
      service: name=rsyslog state=started
    - include: otro_playbook.yml