---
- name: Include test
  hosts: ubuntu_servers
  vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  tasks:
    - name: Test service status
      service: name=rsyslog state=started
    - include: otro_playbook.yml