# Example usage: ansible-playbook var_files_demo/main.yml
# This playbook use vars from file on the play

---

- name: Var files test
  hosts: ubuntu_servers
  tasks:
    - include_vars: vars.yml
    - name: Test vars file use
      debug: msg="ls -ltr /{{ home_folder }}/{{ user }}/{{ item }}"