# Example usage: ansible-playbook fact_demo/main.yml
# This playbook get information from ansible_facts

---

- name: Facts test
  hosts: ubuntu_servers
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    - name: All
      debug: msg="{{ ansible_facts }}"
    - name: Get custom facts
      set_fact:
        my_fact: value1
      debug: msg=" The custom fact is {{ my_fact }}" 